"""initial schema

Revision ID: ffbed559952c
Revises: 
Create Date: 2026-10-04 06:29:27.250566
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ffbed559952c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Enable pgcrypto for gen_random_uuid()
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(),server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('consents',
    sa.Column('consent_id', sa.UUID(),server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consent_id')
    )
    op.create_table('mood_logs',
    sa.Column('mood_id', sa.UUID(),server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=False),
    sa.Column('stress_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('energy_level BETWEEN 1 AND 5', name='ck_mood_energy'),
    sa.CheckConstraint('stress_level BETWEEN 1 AND 5', name='ck_mood_stress'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mood_id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_mood_user_date')
    )
    op.create_table('schedules',
    sa.Column('schedule_id', sa.UUID(),server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('generated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('schedule_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feasible', sa.Boolean(), nullable=False),
    sa.Column('risk_score_at_generation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('sleep_logs',
    sa.Column('sleep_id', sa.UUID(),server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sleep_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wake_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quality BETWEEN 1 AND 5', name='ck_sleep_quality'),
    sa.CheckConstraint('wake_time > sleep_time', name='ck_sleep_order'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sleep_id')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.UUID(),server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name='ck_subject_difficulty'),
    sa.CheckConstraint('priority BETWEEN 1 AND 5', name='ck_subject_priority'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('assignments',
    sa.Column('assignment_id', sa.UUID(),server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('required_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('priority BETWEEN 1 AND 5', name='ck_assignment_priority'),
    sa.CheckConstraint('required_hours > 0', name='ck_assignment_hours'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('feedback',
    sa.Column('feedback_id', sa.UUID(),server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_feedback_rating'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.schedule_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('study_sessions',
    sa.Column('session_id', sa.UUID(),server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('focus_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration > 0', name='ck_session_duration'),
    sa.CheckConstraint('focus_level BETWEEN 1 AND 5', name='ck_session_focus'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index("idx_consents_user", "consents", ["user_id"])
    op.create_index("idx_subjects_user", "subjects", ["user_id"])
    op.create_index(
        "idx_assignments_user_deadline",
        "assignments", ["user_id", "deadline"],
    )
    op.create_index("idx_assignments_subject", "assignments", ["subject_id"])
    op.create_index(
        "idx_study_sessions_user_date",
        "study_sessions", ["user_id", "start_time"],
    )
    op.create_index(
        "idx_study_sessions_subject",
        "study_sessions", ["subject_id"],
    )
    op.create_index(
        "idx_sleep_logs_user_time",
        "sleep_logs", ["user_id", "sleep_time"],
    )
    op.create_index(
        "idx_mood_logs_user_date",
        "mood_logs", ["user_id", sa.text("log_date DESC")],
    )
    op.create_index(
        "idx_schedules_user_generated",
        "schedules", ["user_id", sa.text("generated_date DESC")],
    )
    op.create_index("idx_feedback_schedule", "feedback", ["schedule_id"])
    op.create_index("idx_feedback_user", "feedback", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_feedback_user", table_name="feedback")
    op.drop_index("idx_feedback_schedule", table_name="feedback")
    op.drop_index("idx_schedules_user_generated", table_name="schedules")
    op.drop_index("idx_mood_logs_user_date", table_name="mood_logs")
    op.drop_index("idx_sleep_logs_user_time", table_name="sleep_logs")
    op.drop_index("idx_study_sessions_subject", table_name="study_sessions")
    op.drop_index("idx_study_sessions_user_date", table_name="study_sessions")
    op.drop_index("idx_assignments_subject", table_name="assignments")
    op.drop_index("idx_assignments_user_deadline", table_name="assignments")
    op.drop_index("idx_subjects_user", table_name="subjects")
    op.drop_index("idx_consents_user", table_name="consents")
    op.drop_table('study_sessions')
    op.drop_table('feedback')
    op.drop_table('assignments')
    op.drop_table('subjects')
    op.drop_table('sleep_logs')
    op.drop_table('schedules')
    op.drop_table('mood_logs')
    op.drop_table('consents')
    op.drop_table('users')
    # ### end Alembic commands ###